Vinci881027 proposal attempt1
yungyuc/nsdhw_22au pull request #164
Opened 2022-10-18 05:43 UTC by Vinci881027

---
A good PR should include the following parts:

- [ ] A clear title
- [ ] A meaningful message for PR, as well as its commits
- [ ] from your specific branch (***not master***) merging to teacher's `HW` branch (***not master***, again)
- [ ] excluding any irrelevant files, such as binaries, text files, or dot files
- [ ] passing tests/CI

2022-10-20 10:42 UTC, yungyuc requested changes
Please add your project to the list in the readme file in the `project` root directory.

2022-10-20 10:42 UTC, yungyuc commented on project/Vinci881027/README.md
> +The problem in this project wants to solve is to calculate histogram of gradient.
Can you formulate the problem or describe the algorithm in pseudo code?

2022-10-20 10:42 UTC, yungyuc commented on project/Vinci881027/README.md
> +For who would like to do edge detection with image processing.
It will help planning by describing what is the use of the edge detection.

2022-10-20 10:42 UTC, yungyuc commented on project/Vinci881027/README.md
> +* Week 2 (11/7):
I'll wait for your adding contents in the schedule.

2022-10-26 09:32 UTC, Vinci881027 commented
OK, I make some changes. Please check it.

2022-10-26 23:06 UTC, yungyuc commented
Please resolve the merge conflict and leave a message after it is done.

2022-10-27 18:56 UTC, Vinci881027 commented
> 

I have resolved the merge conflict.

2022-10-28 14:13 UTC, yungyuc approved these changes
LGTM.  Let me know when you want it to get merged.

2022-10-28 16:39 UTC, Vinci881027 commented
Merging it now is ok. Thank you.

2022-10-29 04:14 UTC, merged